openapi: 3.0.1
info:
  title: AmdocsFirstIntegeration
  description: API Definition of AmdocsFirstIntegeration
  version: 1.0.0
servers:
- url: http://localhost:8290/amdocs
paths:
  /:
    get:
      responses:
        default:
          description: Default response
